### ISSUE TITLE
Problem with Yolo V3

### ISSUE THREAD

**Issue by jessiffmm** [JdeRobot/DetectionMetrics#108]
Hi!!

I'm triying to a yolov3 config and I get some errors. It said that it can't recognized yolo layer, upsampled layer,...
I think that https://github.com/JdeRobot/darknet/ isn't compatible with yolo v3

Regards

**Comment by vinay0410** [comment]
Please post the full error description you are getting for me to help you.

**Comment by jessiffmm** [comment]
82 Type not recognized: [yolo]
Unused field: 'mask = 6,7,8'
Unused field: 'anchors = 10,13,16,30,33,23,30,61,62,45,59,119,116,90,156,198,373,326'
Unused field: 'classes = 80'
Unused field: 'num = 9'
Unused field: 'jitter = .3'
Unused field: 'ignore_thresh = .7'
Unused field: 'truth_thresh = 1'
Unused field: 'random = 1'
   83 route  79
   84 conv    256  1 x 1 / 1    19 x  19 x 512   ->    19 x  19 x 256
   85 Type not recognized: [upsample]
Unused field: 'stride = 2'
   86 route  85 61
   87  netwrigth /opt/datasets/weights//yolov3.weights./DatasetEvaluationApp: Violación de segmento (`core' generado)

**Comment by jessiffmm** [comment]
I'm triying to introduce this type of layer in the detectionsuite.

**Comment by vinay0410** [comment]
I just executed yolov3, and it's not working with JdeRobot/darknet and with DetectionSuite. It's because we are stuck on an outdated fork of darknet, which doesn't support yolov3.

Although Yolo v1 works well.

If Yolov3 is important for the task you are trying to accomplish, then we could shift to using Yolo's original [repository](https://github.com/pjreddie/darknet) instead of our own fork, which would fix this.

Just let me know, if you'd want that.

**Comment by jessiffmm** [comment]
I have downloaded the last https://github.com/pjreddie/darknet and I have adapted it to JdeRobot/darknet for using DarknetApi and install in the computer.

I have this code in my repository (https://github.com/RoboticsURJC-students/2018-tfm-Jessica-Fernandez/tree/master/darknet). 

You can used it if you want.

**Comment by vinay0410** [comment]
Okay, I will look into it tomorrow, and try to integrate it with DetectionSuite.
Although, if you are interested in learning more about DetectionSuite, you can submit a pull integrating this.

This [file](https://github.com/JdeRobot/dl-DetectionSuite/blob/master/DeepLearningSuite/DeepLearningSuiteLib/FrameworkEvaluator/DarknetInferencer.cpp) have to be changed

**Comment by jessiffmm** [comment]
No, I adapt it for DetectionSuite. I've tried it with detectionsuite and it works perfectly. Only you have to use my darknet  instead of https://github.com/JdeRobot/darknet/ .

I do not know how you could substitute https://github.com/JdeRobot/darknet/ for mine. I don't know if I have permissions.

**Comment by vinay0410** [comment]
Okay, great.
So, I will substitute your fork.

But, I was getting the following error while building it.

```
In file included from /home/robo/dev/2018-tfm-Jessica-Fernandez/darknet/DarknetAPI/DarknetAPI.cpp:5:0:
/home/robo/dev/2018-tfm-Jessica-Fernandez/darknet/DarknetAPI/DarknetAPI.h:12:10: fatal error: yolo.h: No such file or directory
 #include "yolo.h"
          ^~~~~~~~
compilation terminated.

```

This file isn't present anywhere in the repository.
Could you please fix this

Thanks !!

**Comment by jessiffmm** [comment]
Ohh sorry! Already solved!

Thank you!!
