### ISSUE TITLE
Terminal=true missing in desktop file?

### ISSUE THREAD

**Issue by probonopd** [JdeRobot/DetectionMetrics#121]
Seems to be a command line tool that does not work when invoked without additional parameters:

```
./BeingTested.AppImage WARNING: Logging before InitGoogleLogging() is written to STDERR
E0319 07:07:05.914254     8 SampleGenerationApp.cpp:71] ERROR: the option '--configFile' is required but missing
E0319 07:07:05.914438     8 SampleGenerationApp.cpp:72] Options:
  --help                  Print help messages
  -c [ --configFile ] arg
Parent pid 8362, child pid 8367
Parent is shutting down, bye...
AppImage unmounted
NUMBER_OF_WINDOWS: 0
```

Seems to be missing `Terminal=true` in the desktop file?

Reference:
https://github.com/AppImage/appimage.github.io/pull/777

**Comment by vinay0410** [comment]
Hi @probonopd 
I have updated the Desktop File.
But the command line executable also needs a config file to run, like below:
`./DatasetEvaluationApp -c <filePath>`

**Comment by probonopd** [comment]
Thanks @vinay0410. If you could ping me once a new AppImage is available for download on the releases page, then I could re-run our automated tests. Thank you. 👍

**Comment by vinay0410** [comment]
The new app image is available at the releases page @probonopd

**Comment by probonopd** [comment]
Are yo sure it was uploaded? The most recent continuous build is 3 days old whereas this tickets is 2 days old.

**Comment by vinay0410** [comment]
@probonopd , please check again, there was an error during build, but travis was still inferring that as a successful build.
I have verified, releases page has also been updated.

**Comment by probonopd** [comment]
Getting

![](https://github.com/AppImage/appimage.github.io/blob/913a48e2b6606ba1595b7ff67447915f36edb901/database/DetectionSuite/screenshot.png?raw=true)

Is this normal?

**Comment by vinay0410** [comment]
Ye @probonopd ,
This is normal, since this is Command Line Tool, it expects a config file to run, and that has to passed as an arg. 
Since, no config file was passes, the Command Line parser throws an error.
