### ISSUE TITLE
Separate tab(workspace) for labelling functionality

### ISSUE THREAD

**Issue by sleep-404** [JdeRobot/DetectionMetrics#159]
Currently labelling functionality is existing within Deployer , so we need to create a different workspace for it in the GUI

**Comment by sleep-404** [comment]
First , before taking on semi-automatic labelling I think , the gui for labelling functionality has to be made . So I have started to work on creating a separate GUI for labelling functionality.

**Comment by sergiopaniego** [comment]
Sounds like a good idea. 
There are some questions that we have to answer about this new tab. 
Which options will you add in this tab? 
Would it look similar to Deployer's tab?
The Deployers tab will lose the current labelling functionality? I think we should only have this functionality in one tab, so if you create a new one we can add this functionality only in that tab.

**Comment by sergiopaniego** [comment]
It is also important to document the new tab on the Web page

**Comment by sleep-404** [comment]
All the options present in deployer will be added to Labelling as well for now, and deployer will be losing the labelling functionality option. And after it gets finished , we can try to add one more option where the user can select among different object tracking algorithms available in opencv.
