### ISSUE TITLE
Update COCODatasetReader.cpp 

### ISSUE THREAD

**Issue by sleep-404** [JdeRobot/DetectionMetrics#167]
Currently COCODatasetReader searches for an "annotation" member in the config file and returns "Invalid Annotations file Passed" exceptions, which it should do, if Evaluator calls the functions as in that case annotations are necessary but it does the same when Detector calls the reader function which it should not as Detector just runs the model on the Dataset.

**Comment by hmrishavbandy** [comment]
Hi, I am interested in this issue. Would passing along a separate marker( bool variable) be enough to avoid this problem? The marker would certify whether the annotations are necessary or not.
