### ISSUE TITLE
Update Tensorflow version to 2.1 and Python3

### ISSUE THREAD

**Issue by sergiopaniego** [JdeRobot/DetectionMetrics#176]
Tensorflow 2.1 is the current stable version of tf. 
Since we have some functionality in tf, it would be a good idea to update the current version of tf. 
Additionally, since Python 2.7 is no longer maintained, update it to Python 3.x

**Comment by hmrishavbandy** [comment]
Hi, I would like to work on this. This requires me to just remove and replace the obsolete features in python 2.7 and Tensorflow right?

**Comment by hmrishavbandy** [comment]
I have updated to python3.6.9  and will submit the pull request to the same. I hope it is alright to solve this part by part.

**Comment by sergiopaniego** [comment]
You can submit two pull request, one for each problem.

**Comment by hmrishavbandy** [comment]
Yes, but i have actually not created a branch from master in my fork of the project before committing and now i cant commit before the pull request is merged :(
