### ISSUE TITLE
Problem in Installation

### ISSUE THREAD

**Issue by adityarajsahu** [JdeRobot/DetectionMetrics#201]
Can anyone tell me the exact process of installing DetectionStudio? I am having problem installing that.

**Comment by sergiopaniego** [comment]
Could you give further information about the problems you are facing?

The complete installation guide is [here](https://jderobot.github.io/DetectionStudio/installation/).
I recommend following the instructions from **Compile and Install from source** section.

**Comment by adityarajsahu** [comment]
When I ran the command "./DetectionStudioxxxxx -c configFile" in the terminal, I got no response.

Can you tell me which file should I download out of the two in this link : https://github.com/JdeRobot/DetectionStudio/releases/tag/continuous

And, please attach the link to "Compile and Install from source".

**Comment by sergiopaniego** [comment]
That version quite old and it's possible that is no longer running properly. I suggest you follow the instructions from **Compile and Install from source** section.

You can find that section in the the previous webpage: https://jderobot.github.io/DetectionStudio/installation/, just below the part you're referring to. It's a big title in bold.
