### ISSUE TITLE
The documentation for labelling functionality in DetectionSuite could be improved

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/DetectionMetrics#93]
This way DetectionSuite could be easily used by the [Smart-Traffic-Sensor](https://github.com/JdeRobot/smart-traffic-sensor) developers, who work with the detection of vehicles on images. This labelling capability has been proposed for [ObjectDetector](https://github.com/JdeRobot/dl-objectdetector/issues/41), but it is already implemented in DetectionSuite, and this is a better place for it I think.

**Comment by vinay0410** [comment]
We can also integrate Detectiosuite's Detection functionality to automatically detect objects and generate labels for the same.
Just like proposed in ObjectDetector.
DetectionSuite has a labeling tool, to which Detection can be added to automatically generate labels for objects, and the user can use them further.
