### ISSUE TITLE
Better Exception handling for python Code

### ISSUE THREAD

**Issue by vinay0410** [JdeRobot/DetectionMetrics#96]
Exceptions raised in python code doesn't halt the calling c++ code, causing the c++ code to run and causing a segmentation fault eventually

**Comment by sleep-404** [comment]
To which python code is this referring to ? 
Would exiting from the program when exceptions are raised , solve the problem ?

**Comment by Surajpatra700** [comment]
I would like to work upon this issue. Please tell me on which python file is creating this issue ?
