### ISSUE TITLE
Problem with Yolo

### ISSUE THREAD

**Issue by jessiffmm** [JdeRobot/DetectionMetrics#98]
Hi!!!

I'm trying to use Yolo in Deploy. But, when I press Process the windows closes. I don't get any mistakes, and that has surprised me. What can happen?

Regards

**Comment by jessiffmm** [comment]
Hi,

I use the next config:
![captura de pantalla de 2018-11-19 23-33-56](https://user-images.githubusercontent.com/15524618/48739264-bd780400-ec53-11e8-95aa-59527b2910d2.png)

**Comment by vinay0410** [comment]
Yolo needs a config file, you’ve to download the file config file for yolo-tiny.
From the same place you’ve downloaded yolo-tiny.weights

**Comment by jessiffmm** [comment]
@vinay0410 Okk Thanks!!
